### ISSUE TITLE
Make this repo citeable

### ISSUE THREAD

**Issue by sloede** [Datseris/whyjulia-manifesto#7]
Thanks again for putting in the effort to create this repository! I think it is also great that you put it under the CC0 license, to allow maximum ease of sharing!

Sometimes, though, it would be nice to be able properly cite this repo. Thus I suggest setting this with a `.zenodo.json` file and creating a release that then gets assigned a DOI by Zenodo. That way it would also be easier to reference this manifesto, e.g., from a talk.

If you need help with that, I'd be happy to lend a hand.

**Comment by Datseris** [comment]
Thanks, yeap I will add a zenodo doi!!!
